/*
 * generated by Xtext 2.12.0
 */
package de.dentrassi.varlink.idl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractVarlinkIdlScopeProvider extends XbaseBatchScopeProvider {
}
