/*
 * generated by Xtext 2.12.0
 */
package de.dentrassi.varlink.idl.tests

import com.google.inject.Inject
import de.dentrassi.varlink.idl.varlinkIdl.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(VarlinkIdlInjectorProvider)
class VarlinkIdlParsingTest {
	@Inject
	ParseHelper<Model> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
