/*
 * generated by Xtext 2.12.0
 */
package de.dentrassi.varlink.idl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VarlinkIdlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/dentrassi/varlink/idl/parser/antlr/internal/InternalVarlinkIdl.tokens");
	}
}
