/*
 * generated by Xtext 2.12.0
 */
package de.dentrassi.varlink.idl.ui.tests;

import com.google.inject.Injector;
import de.dentrassi.varlink.idl.ui.internal.IdlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class VarlinkIdlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IdlActivator.getInstance().getInjector("de.dentrassi.varlink.idl.VarlinkIdl");
	}

}
