/*
 * generated by Xtext 2.12.0
 */
package de.dentrassi.varlink.idl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class VarlinkIdlRuntimeModule extends AbstractVarlinkIdlRuntimeModule {
}
