/**
 * generated by Xtext 2.12.0
 */
package de.dentrassi.varlink.idl.varlinkIdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Alias Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.dentrassi.varlink.idl.varlinkIdl.VarlinkIdlPackage#getTypeAliasDefinition()
 * @model
 * @generated
 */
public interface TypeAliasDefinition extends EObject
{
} // TypeAliasDefinition
